<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_College_college_id</name>
   <tag></tag>
   <elementGuidId>9bd49f92-88cd-4fd0-8d0f-9fadd27646b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='college_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;college_id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aab62499-411b-43d3-9e16-6c5e0601108d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary-outline text-primary bg-white hover:bg-gray-100 hover:text-gray-800 hover:border-gray-800 btn-sm font-bold text-md w-40 disabled:cursor-not-allowed disabled:opacity-50</value>
      <webElementGuid>d5ffa19b-7d4f-4d73-a95e-7c5a559f5e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b07a3d7-2aec-47f2-b7d8-b70d0fa3267e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>college_id</value>
      <webElementGuid>6bc7bd6d-ba3a-41ce-ba2b-933429f1cf30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select College</value>
      <webElementGuid>5a7c241a-3fb2-4e25-94da-31ff94678d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r6:-form-item&quot;)/button[@class=&quot;btn btn-primary-outline text-primary bg-white hover:bg-gray-100 hover:text-gray-800 hover:border-gray-800 btn-sm font-bold text-md w-40 disabled:cursor-not-allowed disabled:opacity-50&quot;]</value>
      <webElementGuid>b28ffeea-8a01-42c5-94e0-202ceada0e70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='college_id']</value>
      <webElementGuid>873b08f2-15b7-4132-a8ef-5dfbe33edcf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r6:-form-item']/button</value>
      <webElementGuid>79a22aac-d254-45a1-860d-9e865987c0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='College'])[1]/following::button[1]</value>
      <webElementGuid>15c700ae-0074-4888-829e-57e2821d30b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roll number'])[1]/following::button[1]</value>
      <webElementGuid>d692237a-0505-475b-b79e-d42c13e3ba88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone number'])[1]/preceding::button[1]</value>
      <webElementGuid>8400515a-b487-49b1-a6aa-3f8d03c6a450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::button[1]</value>
      <webElementGuid>07fc6593-8318-44f2-8854-d35434d424af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select College']/parent::*</value>
      <webElementGuid>5b7b4265-a4e9-4a34-a85a-5188103b5cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>11c19137-5bc9-4872-a5af-acaaa4d78ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'college_id' and (text() = 'Select College' or . = 'Select College')]</value>
      <webElementGuid>82ff90f3-00fd-48a2-9488-f0407f07e4ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
