<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Roll number_roll_number</name>
   <tag></tag>
   <elementGuidId>76d0f071-9b89-4e94-ad4b-912d80d44098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='roll_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;roll_number&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7a3d380-4471-4ccb-9aa4-9f95acc576e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac471d2d-8aff-4cc9-8ac3-08d2e50ae524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter roll number</value>
      <webElementGuid>c1e7c661-b277-46b0-aabe-a015049fe5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>roll_number</value>
      <webElementGuid>a48a972e-16ec-4a7e-8d4d-c2d3e06393a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r5:-form-item&quot;)/label[@class=&quot;input input-secondary flex gap-4 justify-between items-center border-secondary rounded input-sm&quot;]/div[@class=&quot;flex items-center justify-between w-full&quot;]/input[1]</value>
      <webElementGuid>f698140d-d610-487f-b8ad-c2d07028adc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='roll_number']</value>
      <webElementGuid>8c5f2b83-b2fa-49db-8dff-bafc65b50ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r5:-form-item']/label/div/input</value>
      <webElementGuid>9d8a8414-13ed-492f-8dcc-a5579f931147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label/div/input</value>
      <webElementGuid>7d7cee03-97b7-425f-a08a-e863fa2fc243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter roll number' and @name = 'roll_number']</value>
      <webElementGuid>c98a1647-700e-4adc-8582-d4353444d9a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
